### ISSUE TITLE
Possible bug (please check): FPA calculation incorrect

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#25]
I were at EDDM (GS 3.0°) and I set the FPA to -3.0 when I were on the GS.

### Expected Behavior
It follows the GS with just little derivation.

### Current Behavior
The sink rate wasn't high enough to stay on the GS, I ended up too high.

### Steps to Reproduce
1. Lookup the GS angle of an airport
2. Fly into the ILS
3. Enable LOC
4. As soon as the vertical indication of the ILS is almost in the middel, turn the FPA to the angle you've looked up earlier.
5. Does the ILS indication derivate much?

**Comment by it0uchpods** [comment]
Probably it is wrong.
I'll check it once I find out how it should be calculated.

I won't add the bug label quite yet until I'm sure it's wrong.

Josh

**Comment by legoboyvdlp** [comment]
I wonder if the autopilot is using pitch angle instead of actual flight path angle? Just a thought.

**Comment by it0uchpods** [comment]
No, that would cause horrifying things.
It's due to the FPA calculation in IT-AUTOFLIGHT, I actually ripped it out of another plane at some point, it's probably not right. I'm going to open an issue on that repo instead, as this affects all planes with IT-AUTOFLIGHT.

**Comment by legoboyvdlp** [comment]
Alright, thanks!

**Comment by it0uchpods** [comment]
Thanks so much @merspieler 
You are right, the entire IT-AUTOFLIGHT FPA calculation is completely wrong, I fixed it and it should be on git here and on all ITAF planes shortly.

Thanks so much!
Josh

**Comment by it0uchpods** [comment]
Fixed in ITAF V3.2

**Comment by it0uchpods** [comment]
Now fixed.

**Comment by merspieler** [comment]
much better... still not perfect.. 
i can think of following 2 problems:
* fg g/s isn't precise
* You don't use gs -> wind makes a difference

I've tested it just once with ~6kn tail wind. once i was on the g/s i deveriated just slightly upwards which could be caused by the tailwind.

**Comment by it0uchpods** [comment]
Can you watch /it-autoflight/internal/fpa while you do it? Does the system keep the number close to the value you set?

Thanks,
Josh

**Comment by merspieler** [comment]
I've retried it...  the /it-autoflight/internal/fpa property shows the correct value (but needs quite much time to get on this value [probably too much if you are on approach in mountain range] eg. in reaction to speed reduction or flaps extension) 

i've ended up too high again (9kn tail wind this time)

could you please check if you use ground speed and nothing else in the calculations

**Comment by merspieler** [comment]
there we've got the problem... both are relative to the air, not to the ground.

It's the fpa relative to the air but it should be relative to the ground.

**Comment by it0uchpods** [comment]
Does the real plane use FPA relative to the air? If so, do you have a calculation for that?

J

**Comment by merspieler** [comment]
This topic seems to be more difficult... https://www.pprune.org/tech-log/531691-airbus-flight-path-angle.html#post8261737

I'm still at reading the whole thread

**Comment by it0uchpods** [comment]
OK neat, I will experiment when I get some time to work on this again.
